# set base image from docker_hub or anywhere else
FROM centos:8
LABEL zhangruo zhangruo@ncti-gba.cn

#which output subdir to use, e.g. debug_lite, release_lite, release, debug
ENV SRC_SUB release_lite

#set variable 
ENV MYPATH /usr/local/intarkdb_lite
ENV INTARK_LIB_PATH $MYPATH/lib
ENV INTARK_BIN_PATH $MYPATH/bin

#copy source
COPY ./output/inc $MYPATH/inc
COPY ./output/lib $INTARK_LIB_PATH
COPY ./output/$SRC_SUB/lib $INTARK_LIB_PATH

#set mirror address
RUN sed -i -e "s/mirrorlist=/#mirrorlist=/g" /etc/yum.repos.d/CentOS-Linux-*.repo
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-Linux-*.repo
#update yum sources
RUN yum update -y

#set env variable
WORKDIR $INTARK_BIN_PATH
ENV PATH $PATH:$INTARK_LIB_PATH:$INTARK_BIN_PATH
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$INTARK_LIB_PATH:$MYPATH/inc

#install python36, git, openssh-client
RUN yum -y install python36 git 
# RUN yum -y install openssh-client

# copy ssh key into docker container image
# COPY id_rsa /root/.ssh/id_rsa
# RUN chmod 600 /root/.ssh/id_rsa
# # Add Git server to known host list
# RUN ssh-keyscan codehub-cn-south-1.devcloud.huaweicloud.com >> /root/.ssh/known_hosts

# clone function test framework
# RUN git clone git@codehub-cn-south-1.devcloud.huaweicloud.com:qrssjkjcbxm_liyuxiang00001/InstarDB_Test_Framework.git $INTARK_BIN_PATH

# or copy function test framework
ADD InstarDB_Test_Framework.tar.gz $INTARK_BIN_PATH
RUN rm -f $INTARK_BIN_PATH/InstarDB_Test_Framework/log/*
RUN rm -f $INTARK_BIN_PATH/InstarDB_Test_Framework/report/*

# set control file
#RUN sed -i -e "s|CONTROL_FILES = (.*/gstor/data/ctrl1)|CONTROL_FILES = ($INTARK_BIN_PATH/InstarDB_Test_Framework/gstor/data/ctrl1)|g" $INTARK_BIN_PATH/InstarDB_Test_Framework/gstor.ini
# setup dependency
RUN pip3 install --user -r $INTARK_BIN_PATH/InstarDB_Test_Framework/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/
#set library path
RUN echo "libpath:${INTARK_LIB_PATH}" > $INTARK_BIN_PATH/InstarDB_Test_Framework/configure/instarDB_config.txt 

# shutdown transparent hugepage
# RUN echo never > /sys/kernel/mm/transparent_hugepage/enabled 
# RUN echo never > /sys/kernel/mm/transparent_hugepage/defrag

# execute cmd whencontainer running 
CMD python3 $INTARK_BIN_PATH/InstarDB_Test_Framework/run/instarDB_run.py
