# set base image from docker_hub or anywhere else
FROM centos:8
LABEL zhangruo zhangruo@ncti-gba.cn

#set mirror address
RUN sed -i -e "s/mirrorlist=/#mirrorlist=/g" /etc/yum.repos.d/CentOS-Linux-*.repo
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-Linux-*.repo

#which output subdir to use, e.g. debug_lite, release_lite, release, debug
ENV SRC_SUB debug_lite

#set variable 
ENV MYPATH /usr/local/intarkdb_lite
ENV INTARK_LIB_PATH $MYPATH/lib
ENV INTARK_BIN_PATH $MYPATH/bin

#copy source
COPY ./output/inc $MYPATH/inc
COPY ./output/lib $INTARK_LIB_PATH
COPY ./output/$SRC_SUB/lib $INTARK_LIB_PATH
COPY ./output/$SRC_SUB/bin/InstarDB_CLI $INTARK_BIN_PATH/InstarDB_CLI
COPY ./output/$SRC_SUB/bin/stress_insert_test $INTARK_BIN_PATH/stress_insert_test
COPY ./output/$SRC_SUB/bin/stress_prepare_select_test $INTARK_BIN_PATH/stress_prepare_select_test
COPY ./output/$SRC_SUB/bin/stress_select_test $INTARK_BIN_PATH/stress_select_test

#set env variable
WORKDIR $INTARK_BIN_PATH
ENV PATH $PATH:$INTARK_LIB_PATH:$INTARK_BIN_PATH
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$INTARK_LIB_PATH:$MYPATH/inc

#shutdown transparent hugepage
#RUN echo never > /sys/kernel/mm/transparent_hugepage/enabled 
#RUN echo never > /sys/kernel/mm/transparent_hugepage/defrag

#execute cmd whencontainer running 
CMD $INTARK_BIN_PATH/InstarDB_CLI
